/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PeminjamanRuanganImport } from './routes/peminjaman-ruangan'
import { Route as IndexImport } from './routes/index'
import { Route as SuperadminIndexImport } from './routes/superadmin/index'
import { Route as SuperadminRuanganIndexImport } from './routes/superadmin/ruangan/index'
import { Route as SuperadminRuanganTambahRuanganImport } from './routes/superadmin/ruangan/tambah-ruangan'
import { Route as SuperadminRuanganUpdateRuanganIdImport } from './routes/superadmin/ruangan/update-ruangan.$id'
import { Route as SuperadminRuanganDetailRuanganIdImport } from './routes/superadmin/ruangan/detail-ruangan.$id'

// Create/Update Routes

const PeminjamanRuanganRoute = PeminjamanRuanganImport.update({
  id: '/peminjaman-ruangan',
  path: '/peminjaman-ruangan',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SuperadminIndexRoute = SuperadminIndexImport.update({
  id: '/superadmin/',
  path: '/superadmin/',
  getParentRoute: () => rootRoute,
} as any)

const SuperadminRuanganIndexRoute = SuperadminRuanganIndexImport.update({
  id: '/superadmin/ruangan/',
  path: '/superadmin/ruangan/',
  getParentRoute: () => rootRoute,
} as any)

const SuperadminRuanganTambahRuanganRoute =
  SuperadminRuanganTambahRuanganImport.update({
    id: '/superadmin/ruangan/tambah-ruangan',
    path: '/superadmin/ruangan/tambah-ruangan',
    getParentRoute: () => rootRoute,
  } as any)

const SuperadminRuanganUpdateRuanganIdRoute =
  SuperadminRuanganUpdateRuanganIdImport.update({
    id: '/superadmin/ruangan/update-ruangan/$id',
    path: '/superadmin/ruangan/update-ruangan/$id',
    getParentRoute: () => rootRoute,
  } as any)

const SuperadminRuanganDetailRuanganIdRoute =
  SuperadminRuanganDetailRuanganIdImport.update({
    id: '/superadmin/ruangan/detail-ruangan/$id',
    path: '/superadmin/ruangan/detail-ruangan/$id',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/peminjaman-ruangan': {
      id: '/peminjaman-ruangan'
      path: '/peminjaman-ruangan'
      fullPath: '/peminjaman-ruangan'
      preLoaderRoute: typeof PeminjamanRuanganImport
      parentRoute: typeof rootRoute
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminIndexImport
      parentRoute: typeof rootRoute
    }
    '/superadmin/ruangan/tambah-ruangan': {
      id: '/superadmin/ruangan/tambah-ruangan'
      path: '/superadmin/ruangan/tambah-ruangan'
      fullPath: '/superadmin/ruangan/tambah-ruangan'
      preLoaderRoute: typeof SuperadminRuanganTambahRuanganImport
      parentRoute: typeof rootRoute
    }
    '/superadmin/ruangan/': {
      id: '/superadmin/ruangan/'
      path: '/superadmin/ruangan'
      fullPath: '/superadmin/ruangan'
      preLoaderRoute: typeof SuperadminRuanganIndexImport
      parentRoute: typeof rootRoute
    }
    '/superadmin/ruangan/detail-ruangan/$id': {
      id: '/superadmin/ruangan/detail-ruangan/$id'
      path: '/superadmin/ruangan/detail-ruangan/$id'
      fullPath: '/superadmin/ruangan/detail-ruangan/$id'
      preLoaderRoute: typeof SuperadminRuanganDetailRuanganIdImport
      parentRoute: typeof rootRoute
    }
    '/superadmin/ruangan/update-ruangan/$id': {
      id: '/superadmin/ruangan/update-ruangan/$id'
      path: '/superadmin/ruangan/update-ruangan/$id'
      fullPath: '/superadmin/ruangan/update-ruangan/$id'
      preLoaderRoute: typeof SuperadminRuanganUpdateRuanganIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/peminjaman-ruangan': typeof PeminjamanRuanganRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/superadmin/ruangan/tambah-ruangan': typeof SuperadminRuanganTambahRuanganRoute
  '/superadmin/ruangan': typeof SuperadminRuanganIndexRoute
  '/superadmin/ruangan/detail-ruangan/$id': typeof SuperadminRuanganDetailRuanganIdRoute
  '/superadmin/ruangan/update-ruangan/$id': typeof SuperadminRuanganUpdateRuanganIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/peminjaman-ruangan': typeof PeminjamanRuanganRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/superadmin/ruangan/tambah-ruangan': typeof SuperadminRuanganTambahRuanganRoute
  '/superadmin/ruangan': typeof SuperadminRuanganIndexRoute
  '/superadmin/ruangan/detail-ruangan/$id': typeof SuperadminRuanganDetailRuanganIdRoute
  '/superadmin/ruangan/update-ruangan/$id': typeof SuperadminRuanganUpdateRuanganIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/peminjaman-ruangan': typeof PeminjamanRuanganRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/superadmin/ruangan/tambah-ruangan': typeof SuperadminRuanganTambahRuanganRoute
  '/superadmin/ruangan/': typeof SuperadminRuanganIndexRoute
  '/superadmin/ruangan/detail-ruangan/$id': typeof SuperadminRuanganDetailRuanganIdRoute
  '/superadmin/ruangan/update-ruangan/$id': typeof SuperadminRuanganUpdateRuanganIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/peminjaman-ruangan'
    | '/superadmin'
    | '/superadmin/ruangan/tambah-ruangan'
    | '/superadmin/ruangan'
    | '/superadmin/ruangan/detail-ruangan/$id'
    | '/superadmin/ruangan/update-ruangan/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/peminjaman-ruangan'
    | '/superadmin'
    | '/superadmin/ruangan/tambah-ruangan'
    | '/superadmin/ruangan'
    | '/superadmin/ruangan/detail-ruangan/$id'
    | '/superadmin/ruangan/update-ruangan/$id'
  id:
    | '__root__'
    | '/'
    | '/peminjaman-ruangan'
    | '/superadmin/'
    | '/superadmin/ruangan/tambah-ruangan'
    | '/superadmin/ruangan/'
    | '/superadmin/ruangan/detail-ruangan/$id'
    | '/superadmin/ruangan/update-ruangan/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PeminjamanRuanganRoute: typeof PeminjamanRuanganRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
  SuperadminRuanganTambahRuanganRoute: typeof SuperadminRuanganTambahRuanganRoute
  SuperadminRuanganIndexRoute: typeof SuperadminRuanganIndexRoute
  SuperadminRuanganDetailRuanganIdRoute: typeof SuperadminRuanganDetailRuanganIdRoute
  SuperadminRuanganUpdateRuanganIdRoute: typeof SuperadminRuanganUpdateRuanganIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PeminjamanRuanganRoute: PeminjamanRuanganRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
  SuperadminRuanganTambahRuanganRoute: SuperadminRuanganTambahRuanganRoute,
  SuperadminRuanganIndexRoute: SuperadminRuanganIndexRoute,
  SuperadminRuanganDetailRuanganIdRoute: SuperadminRuanganDetailRuanganIdRoute,
  SuperadminRuanganUpdateRuanganIdRoute: SuperadminRuanganUpdateRuanganIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/peminjaman-ruangan",
        "/superadmin/",
        "/superadmin/ruangan/tambah-ruangan",
        "/superadmin/ruangan/",
        "/superadmin/ruangan/detail-ruangan/$id",
        "/superadmin/ruangan/update-ruangan/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/peminjaman-ruangan": {
      "filePath": "peminjaman-ruangan.tsx"
    },
    "/superadmin/": {
      "filePath": "superadmin/index.tsx"
    },
    "/superadmin/ruangan/tambah-ruangan": {
      "filePath": "superadmin/ruangan/tambah-ruangan.tsx"
    },
    "/superadmin/ruangan/": {
      "filePath": "superadmin/ruangan/index.tsx"
    },
    "/superadmin/ruangan/detail-ruangan/$id": {
      "filePath": "superadmin/ruangan/detail-ruangan.$id.tsx"
    },
    "/superadmin/ruangan/update-ruangan/$id": {
      "filePath": "superadmin/ruangan/update-ruangan.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
